name: Go Build 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.5' # The Go version to download (if necessary) and use.
    - name: build
      shell: bash
      run: |
        bash go-build.bash goPrivateBinCli
        for i in `ls goPrivateBinCli-*` ; do gzip -9 $i ; done
    - uses: actions/checkout@v2
      with:
        ref: latest-binaries
        path: latest-binaries
    - name: update latest binaries
      shell: bash
      run: |
        cd latest-binaries
        rm -f * .* || echo
        cp ../goPrivateBinCli-*gz .
        git add -A .
        git config --local user.email "privapps"
        git config --local user.name "privapps"
        git commit -m "sync with code $(date +'%F')" && \
        git push "https://${GITHUB_ACTOR}:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:latest-binaries || echo
